config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :notas do
    member {get 'download_txt'}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nota.rb
class Nota < ApplicationRecord
  belongs_to :user
  has_attached_file :planilha_itens
  validates_attachment :planilha_itens, content_type: { content_type: ['application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.ms-excel'] }
  
  attr_accessor :cambio
  attr_accessor :itens
  attr_accessor :dados
  
  
  def calcula
    calculo = NotaPlanilhaCalculo.new(self)
    @dados = calculo.calcula
  end
  
  def to_txt
    raise RuntimeError, 'Nota ainda não possui planilha' unless planilha_itens.present?
    raise RuntimeError, 'Você deve invocar #calcula antes de tentar gerar o txt' if dados.nil?

    conversor = ConversorTxt.new(self)
    conversor.converte_para_txt
    
    # txt = IO.read('/home/dudu/w/nfe-espelho/spec/fixtures/files/joao/nota-txt-exportada.txt')
#    txt.strip.gsub(/\n/, "\r\n")
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notas_controller.rb
class NotasController < ApplicationController
  before_action :set_nota, only: [:show, :edit, :update, :destroy, :download_txt]

  # GET /notas
  # GET /notas.json
  def index
    @notas = Nota.all
  end

  # GET /notas/1
  # GET /notas/1.json
  def show
  end

  # Retorna txt da nota
  # GET /notas/1/download_txt
  def download_txt
    @nota.calcula
    send_data @nota.to_txt, type: 'text/plain', filename: "nota-fiscal-#{@nota.id}.txt"
  end

  # GET /notas/new
  def new
    @nota = Nota.new()
    @nota.user = current_user
  end

  # GET /notas/1/edit
  def edit
  end

  # POST /notas
  # POST /notas.json
  def create
    @nota = Nota.new(nota_params)
    @nota.user = current_user

    respond_to do |format|
      if @nota.save
        format.html { redirect_to @nota, notice: 'Nota foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @nota }
      else
        format.html { render :new }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notas/1
  # PATCH/PUT /notas/1.json
  def update
    respond_to do |format|
      if @nota.update(nota_params)
        format.html { redirect_to @nota, notice: 'Nota was successfully updated.' }
        format.json { render :show, status: :ok, location: @nota }
      else
        format.html { render :edit }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notas/1
  # DELETE /notas/1.json
  def destroy
    @nota.destroy
    respond_to do |format|
      format.html { redirect_to notas_url, notice: 'Nota foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota
      @nota = Nota.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nota_params
      params.fetch(:nota, {}).permit(:titulo, :planilha_itens)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NfeEspelho</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/notas/_form.html.erb
<%= form_with(model: nota, local: true,  multipart: true ) do |form| %>
  <% if nota.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nota.errors.count, "error") %> prohibited this nota from being saved:</h2>

      <ul>
      <% nota.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :titulo %>
  <%= form.text_field :titulo %>

  <%= form.label :planilha_itens %>
  <%= form.file_field :planilha_itens %>

    

  <div class="actions">
    <%= form.submit 'Salvar' %>
  </div>
<% end %>

app/views/notas/edit.html.erb
<h1>Editing Nota</h1>

<%= render 'form', nota: @nota %>

<%= link_to 'Show', @nota %> |
<%= link_to 'Back', notas_path %>

app/views/notas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notas.each do |nota| %>
      <tr>
        <td><%= link_to nota.titulo, nota %></td>
        <td><%= link_to 'Edit', edit_nota_path(nota) %></td>
        <td><%= link_to 'Destroy', nota, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova nota', new_nota_path %>

app/views/notas/new.html.erb
<h1>New Nota</h1>

<%= render 'form', nota: @nota %>

<%= link_to 'Back', notas_path %>

app/views/notas/show.html.erb
<p id="notice"><%= notice %></p>

<%= @nota.titulo %>


<%= link_to 'Baixar TXT para gerar nota fiscal', download_txt_nota_path(@nota) %> |

<%= link_to 'Editar', edit_nota_path(@nota) %> |
<%= link_to 'Voltar', notas_path %>